excerpt_separator: ""
pygments: rouge
markdown: kramdown
url: http://lawsonproject-chapt2.github.io/
title: The Lawson Project
tagline: A look back at the TV Show "Small Wonder"
description: My awesome new site
paginate: 5
