excerpt_separator: ""
pygments: rouge
markdown: kramdown
url: http://lawsonproject-chapter2.github.io/ChapterTwo/
title: The Lawson Project
tagline: A look back at the TV Show "Small Wonder"
description: My awesome new site
paginate: 5
